services:
  backend-go:
    build: ./backend-go
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db/chatdb?sslmode=disable
    

  backend-rust:
    build: ./backend-rust
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6543:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: