version: "3.8"
services:
  backend-go:
    build: ./backend-go
    ports:
      - "8080:8080"

  backend-rust:
    build: ./backend-rust
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
