name: CI/CD Pipeline with Private Docker Registry

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend-go/**'
      - 'backend-rust/**'
  pull_request:
    branches: [ main ]

env:

  # For Docker Hub
  # REGISTRY: docker.io
  # IMAGE_NAME: your-app-name
  
  # For Self-hosted registry
  REGISTRY: localhost:5000
  IMAGE_NAME_FRONTEND: whatsvupp-frontend
  IMAGE_NAME_GO: whatsvupp-backend-go
  IMAGE_NAME_RUST: whatsvupp-backend-rust

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker configuration for insecure registry
      run: |
        sudo mkdir -p /etc/docker
        sudo sh -c 'echo "{\"insecure-registries\":[\"${{ env.REGISTRY }}\"]}" > /etc/docker/daemon.json'
        sudo systemctl restart docker
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:latest

    - name: Build and push backend-go image
      uses: docker/build-push-action@v5
      with:
        context: ./backend-go
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_GO }}:latest

    - name: Build and push backend-rust image 
      uses: docker/build-push-action@v5
      with: 
        context: ./frontend
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_RUST }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to staging/production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # docker pull ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        # docker-compose up -d
